export default {
    GET_CONFIGURATOR_DATA_REQUEST: 'GET_CONFIGURATOR_DATA_REQUEST',
    GET_CONFIGURATOR_DATA_SUCCESS: 'GET_CONFIGURATOR_DATA_SUCCESS',
    GET_CONFIGURATOR_DATA_ERROR: 'GET_CONFIGURATOR_DATA_ERROR'
}